# Generated by Django 4.2.3 on 2026-01-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('enable', 'Enable'), ('disable', 'Disable')], default='enable', max_length=20),
        ),
    ]
