# Generated by Django 4.2.3 on 2026-01-14 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
    ]
